
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/ahmetalpbalkan/go-linq"

[[constraint]]
  name = "github.com/aisk/logp"

[[constraint]]
  name = "github.com/aisk/wizard"

[[constraint]]
  name = "github.com/cbroglie/mustache"

[[constraint]]
  name = "github.com/cheggaaa/pb"
  version = "1.0.5"
[[constraint]]
  name = "github.com/coreos/go-semver"
  version = "0.2.0"

[[constraint]]
  name = "github.com/facebookgo/parseignore"

[[constraint]]
  name = "github.com/facebookgo/symwalk"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.0.0"

[[constraint]]
  name = "github.com/getsentry/raven-go"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.1.0"

[[constraint]]
  name = "github.com/juju/persistent-cookiejar"

[[constraint]]
  name = "github.com/leancloud/go-upload"

[[constraint]]
  name = "github.com/levigross/grequests"

[[constraint]]
  name = "github.com/pkg/browser"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.19.1"

[[constraint]]
  branch = "master"
  name = "github.com/cloudfoundry-attic/jibber_jabber"
